export const weekDay = [
  {id: 1, name: 'Seg'},
  {id: 2, name: 'Ter'},
  {id: 3, name: 'Quar'},
  {id: 4, name: 'Quin'},
  {id: 5, name: 'Sex'},
  {id: 6, name: 'Sab'},
  {id: 7, name: 'Dom'},
];

export const formPay = [
  {id: 1, name: 'Dinheiro'},
  {id: 2, name: 'Crédito'},
  {id: 3, name: 'Débito'},
];

export const product = [
  {id: 1, include: 'agua', name: 'Água'},
  {id: 2, include: 'gas', name: 'Gás'},
];

export const ListAdress = [
  'Todos',
  ' 70/RO',
  'Águas Compridas',
  'Aguazinha',
  'Alto da Bondade',
  'Alto da Conquista',
  'Alto Jardim Conquista',
  'Alto da Nação',
  'Alto Nova Olinda',
  'Alto do Sol Nascente',
  'Amaro Branco',
  'Amparo',
  'Bairro Novo',
  'Bonsucesso',
  'Bultrins',
  'Casa Caiada',
  "Caixa D'água",
  'Carmo',
  'Corrego do Abacaxi',
  'Fragoso',
  'Guadalupe',
  'Jardim Atlântico',
  'Jardim Fragoso',
  'Jardim Brasil',
  'Jatobá',
  'Milagres',
  'Monte',
  'Ouro Preto',
  'Passarinho',
  'Peixinhos',
  'Rio Doce',
  'Santa Tereza',
  'Salgadinho',
  'São Benedito',
  'Sapucaia',
  'Sítio Novo',
  'Tabajara',
  'Umuarama',
  'Varadouro',
  'Vila Popular',
  'Zona Rural',
];
